language: elixir

sudo: false

cache:
  directories:
    - deps
    - _build

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.2.6
    - otp_release: 18.3
      elixir: 1.3.1
    - otp_release: 19.0
      elixir: 1.3.1

script:
  - mix coveralls.travis

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report

branches:
  except:
    - galaci
